### ISSUE TITLE
私有镜像不能拉取

### ISSUE THREAD

**Issue by dreamfly32** [cmliu/CF-Workers-docker.io#1]
我已经登录：docker login xx.dev
拉取镜像，docker pull xx.dev/x/x:latest         
报错：repository does not exist or may require 'docker login': denied: requested access to the resource is denied
好像token没传递
![image](https://github.com/cmliu/CF-Workers-docker.io/assets/32086491/67f15d8b-1350-483b-8a0d-fab64a8cd3b7)

**Comment by cmliu** [comment]
> 我已经登录：docker login xx.dev 拉取镜像，docker pull xx.dev/x/x:latest 报错：repository does not exist or may require 'docker login': denied: requested access to the resource is denied 好像token没传递 ![image](https://private-user-images.githubusercontent.com/32086491/339252108-67f15d8b-1350-483b-8a0d-fab64a8cd3b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDc4NTAsIm5iZiI6MTcxODMwNzU1MCwicGF0aCI6Ii8zMjA4NjQ5MS8zMzkyNTIxMDgtNjdmMTVkOGItMTM1MC00ODNiLThhMGQtZmFiNjRhOGNkM2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE5MzkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZTY2ZDhlNzJiOWU2MDhkZDk2MDg3NzU3ZGE1NzliYzA3ZTZjNjgyZmFmMWQ5NjY2YmE3YWYwY2ExMDEzMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QbxvdiMuPKjs1ZElw1tTAF9Oo19vz7q0Q-paPqMpAbc)

这个我研究得比较少，主要都是去拉人家的镜像去白嫖的，所以也不是很清楚要怎么弄呢，可以试试别人的公益镜像，因为CF这个服务很可能会跳IP就把token授权跳失效了。只能看看有没有大佬能PR项目继续优化了
