### ISSUE TITLE
咨询一下，能否解决production.cloudflare.docker.com的问题

### ISSUE THREAD

**Issue by seepine** [cmliu/CF-Workers-docker.io#14]
在通过 docker buildx 构建多平台镜像时，其还会访问 `production.cloudflare.docker.com` 获取镜像 mainfest ，而次域名也被墙了，导致配置了镜像源还是不能完成原来cicd的工作流

```log
::error::buildx failed with: ERROR: failed to solve: seepine/alpine:8-jre: failed to resolve source metadata for docker.io/seepine/alpine:8-jre: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/bc/bcd4dec555f6a0c4832e1*******2933ee6e229109cafd3d76c576a8a5d17a8/data?verify=1719563818-EsDmEn1%252FJ2bglo1sPLZ4N%252BzfkXw%253D": read tcp 172.17.0.5:56596->157.240.12.35:443: read: connection reset by peer
```

**Comment by cmliu** [comment]
> 在通过 docker buildx 构建多平台镜像时，其还会访问 `production.cloudflare.docker.com` 获取镜像 mainfest ，而次域名也被墙了，导致配置了镜像源还是不能完成原来cicd的工作流
> 
> 
> 
> ```log
> 
> ::error::buildx failed with: ERROR: failed to solve: seepine/alpine:8-jre: failed to resolve source metadata for docker.io/seepine/alpine:8-jre: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/bc/bcd4dec555f6a0c4832e1*******2933ee6e229109cafd3d76c576a8a5d17a8/data?verify=1719563818-EsDmEn1%252FJ2bglo1sPLZ4N%252BzfkXw%253D": read tcp 172.17.0.5:56596->157.240.12.35:443: read: connection reset by peer
> 
> ```

后面的我就不会了😂😂😂
