### ISSUE TITLE
暴露的Wokers域

### ISSUE THREAD

**Issue by Anbool** [cmliu/CF-Workers-docker.io#29]
https://github.com/cmliu/CF-Workers-docker.io/blob/a38495f06f917ced6c22904f98e59ab7430da693/_worker.js#L113
该行代码会导致修改 Www-Authenticate 头时被替换为Wokers绑定的域，而自定义的服务器地址将会失效。
https://github.com/cmliu/CF-Workers-docker.io/blob/a38495f06f917ced6c22904f98e59ab7430da693/_worker.js#L8

**Comment by cmliu** [comment]
> https://github.com/cmliu/CF-Workers-docker.io/blob/a38495f06f917ced6c22904f98e59ab7430da693/_worker.js#L113
> 
> 该行代码会导致修改 Www-Authenticate 头时被替换为Wokers绑定的域，而自定义的服务器地址将会失效。
> 
> https://github.com/cmliu/CF-Workers-docker.io/blob/a38495f06f917ced6c22904f98e59ab7430da693/_worker.js#L8

你有需求可以注释掉L113,很多小白不会填那个域名所以我才改成自动填的
