### ISSUE TITLE
一点点小问题

### ISSUE THREAD

**Issue by kabaka9527** [cmliu/CF-Workers-docker.io#4]
docker pull dockerhub.kabaka.xyz/stilleshan/frpc:latest
Error response from daemon: Get "https://dockerhub.kabaka.xyz/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by cmliu** [comment]
> docker pull dockerhub.kabaka.xyz/stilleshan/frpc:latest Error response from daemon: Get "https://dockerhub.kabaka.xyz/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

![image](https://github.com/cmliu/CF-Workers-docker.io/assets/24787744/ec5ba3db-a77e-4c50-ad7a-6f51d19ca86f)

**Comment by kabaka9527** [comment]
> > docker pull dockerhub.kabaka.xyz/stilleshan/frpc:latest Error response from daemon: Get "https://dockerhub.kabaka.xyz/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> ![image](https://github.com/cmliu/CF-Workers-docker.io/assets/24787744/ec5ba3db-a77e-4c50-ad7a-6f51d19ca86f)
> 

嘶……，是要加到/etc/docker/daemon.json里吗
![Screenshot_2024-06-16-00-09-08-442_com.server.auditor.ssh.client.png](https://github.com/cmliu/CF-Workers-docker.io/assets/142149737/24bde551-27b9-4b79-a457-3d50a21adbd3)

**Comment by kabaka9527** [comment]
哦～我知道了，就是国内抽风好像
