### ISSUE TITLE
能否支持URL=nginx只代理首页，保留镜像搜索功能

### ISSUE THREAD

**Issue by nodjoy** [cmliu/CF-Workers-docker.io#64]
期望：
访问 [自定义域名] 跳转至nginx默认页面
访问 [自定义域名]/search?q=nginx 跳转至镜像搜索页面

**Comment by Glendia** [comment]
我仓库有一个，你搜docker，看一下有一个保留搜索进入了首页
[https://push.yimn.me/search?q=nginx](https://push.yimn.me/search?q=nginx)

**Comment by Glendia** [comment]
我仓库有一个  
你搜关键词：docker，看一下有一个保留搜索进入了首页  
[https://push.yimn.me/search?q=nginx](https://push.yimn.me/search?q=nginx)

> 期望：
> 访问 [自定义域名] 跳转至nginx默认页面
> 访问 [自定义域名]/search?q=nginx 跳转至镜像搜索页面
